name: explore
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper : ^1.1.4
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  dynamic_theme: ^1.0.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  align_positioned: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family: Electrolize
      fonts:
        - asset: fonts/Electrolize-Regular.ttf

    - family: Caveat
      fonts:
        - asset : fonts/Caveat-Regular.ttf

    - family: PoppinsExtraBold
      fonts:
      - asset : fonts/Poppins-ExtraBold.ttf

    - family: PoppinsBold
      fonts:
      - asset : fonts/Poppins-Bold.ttf

    - family: PoppinsLight
      fonts:
      - asset : fonts/Poppins-Light.ttf

    - family: Poppins
      fonts:
      - asset : fonts/Poppins-Regular.ttf

  assets:
    - assets/images/
